using System.IO.Packaging;
using System.Text.Json;
using System.Xml.Linq;

namespace Office.Automation.OpenXml;

/// <summary>
/// Self-implemented PPTX writer — zero NuGet dependencies.
///
/// OOXML via in-box System.IO.Packaging + LINQ to XML (dependency policy
/// 2026-08-16). System.IO.Packaging OWNS [Content_Types].xml and every
/// .rels part: register content types at CreatePart and create
/// relationships through CreateRelationship — never hand-write those parts.
/// </summary>
public static class PptxWriter
{
    private static readonly XNamespace A = "http://schemas.openxmlformats.org/drawingml/2006/main";
    private static readonly XNamespace P = "http://schemas.openxmlformats.org/presentationml/2006/main";
    private static readonly XNamespace R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";

    private const string RtSlideLayout = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout";
    private const string RtSlideMaster = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster";
    private const string RtTheme = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme";
    private const string RtNotesSlide = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide";
    private const string RtNotesMaster = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesMaster";
    private const string RtSlide = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide";
    private const string RtOfficeDocument = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument";

    private const string CtRels = "application/vnd.openxmlformats-package.relationships+xml";
    private const string CtPresentation = "application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml";
    private const string CtSlide = "application/vnd.openxmlformats-officedocument.presentationml.slide+xml";
    private const string CtSlideLayout = "application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml";
    private const string CtSlideMaster = "application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml";
    private const string CtNotesSlide = "application/vnd.openxmlformats-officedocument.presentationml.notesSlide+xml";
    private const string CtNotesMaster = "application/vnd.openxmlformats-officedocument.presentationml.notesMaster+xml";
    private const string CtTheme = "application/vnd.openxmlformats-officedocument.theme+xml";

    private const long EmuPerInch = 914400;

    /// <summary>Compile a Deck IR JSON file into a PPTX package.</summary>
    public static void CompileDeck(string irPath, string outPath)
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(irPath));
        var slides = doc.RootElement.GetProperty("document").GetProperty("slides");
        int slideCount = slides.GetArrayLength();
        string deckTitle = "Deck";
        if (doc.RootElement.TryGetProperty("metadata", out var meta) && meta.TryGetProperty("title", out var title))
        {
            deckTitle = title.GetString() ?? deckTitle;
        }
        bool includeNotes = Environment.GetEnvironmentVariable("OFFICE_HOST_NO_NOTES") != "1";

        using var package = Package.Open(outPath, FileMode.Create);
        // Package-level relationship (managed by Packaging; its id is
        // auto-generated and referenced by nothing in our XML).
        package.CreateRelationship(
            new Uri("/ppt/presentation.xml", UriKind.Relative), TargetMode.Internal, RtOfficeDocument);

        // Relationship ids are auto-generated by Packaging: create the
        // relationship first, then write XML referencing the returned id.
        var presentationPart = CreatePart(package, "/ppt/presentation.xml", CtPresentation);
        string masterRelId = presentationPart.CreateRelationship(
            new Uri("slideMasters/slideMaster1.xml", UriKind.Relative), TargetMode.Internal, RtSlideMaster).Id;
        string notesMasterRelId = "";
        var slideRelIds = new string[slideCount];
        for (int i = 0; i < slideCount; i++)
        {
            slideRelIds[i] = presentationPart.CreateRelationship(
                new Uri($"slides/slide{i + 1}.xml", UriKind.Relative), TargetMode.Internal, RtSlide).Id;
        }
        WriteContent(presentationPart, PresentationXml(slideCount, deckTitle, includeNotes, masterRelId, notesMasterRelId, slideRelIds));

        var masterPart = CreatePart(package, "/ppt/slideMasters/slideMaster1.xml", CtSlideMaster);
        string masterLayoutRelId = masterPart.CreateRelationship(
            new Uri("../slideLayouts/slideLayout1.xml", UriKind.Relative), TargetMode.Internal, RtSlideLayout).Id;
        string masterThemeRelId = masterPart.CreateRelationship(
            new Uri("../theme/theme1.xml", UriKind.Relative), TargetMode.Internal, RtTheme).Id;
        WriteContent(masterPart, MasterXml(masterLayoutRelId, masterThemeRelId));

        var layoutPart = CreatePart(package, "/ppt/slideLayouts/slideLayout1.xml", CtSlideLayout);
        string layoutMasterRelId = layoutPart.CreateRelationship(
            new Uri("../slideMasters/slideMaster1.xml", UriKind.Relative), TargetMode.Internal, RtSlideMaster).Id;
        WriteContent(layoutPart, LayoutXml(layoutMasterRelId));

        var themePart = CreatePart(package, "/ppt/theme/theme1.xml", CtTheme);
        WriteContent(themePart, ThemeXml());

        if (includeNotes)
        {
            var notesMasterPart = CreatePart(package, "/ppt/notesMasters/notesMaster1.xml", CtNotesMaster);
            string notesMasterThemeRelId = notesMasterPart.CreateRelationship(
                new Uri("../theme/theme1.xml", UriKind.Relative), TargetMode.Internal, RtTheme).Id;
            WriteContent(notesMasterPart, NotesMasterXml(notesMasterThemeRelId));
        }

        for (int i = 0; i < slideCount; i++)
        {
            var slide = slides[i];
            string notes = slide.TryGetProperty("speaker_notes", out var n) ? n.GetString() ?? "" : "";
            var slidePart = CreatePart(package, $"/ppt/slides/slide{i + 1}.xml", CtSlide);
            string slideLayoutRelId = slidePart.CreateRelationship(
                new Uri("../slideLayouts/slideLayout1.xml", UriKind.Relative), TargetMode.Internal, RtSlideLayout).Id;
            string slideNotesRelId = "";
            if (includeNotes)
            {
                slideNotesRelId = slidePart.CreateRelationship(
                    new Uri($"../notesSlides/notesSlide{i + 1}.xml", UriKind.Relative), TargetMode.Internal, RtNotesSlide).Id;
                var notesPart = CreatePart(package, $"/ppt/notesSlides/notesSlide{i + 1}.xml", CtNotesSlide);
                string notesPartMasterRelId = notesPart.CreateRelationship(
                    new Uri("../notesMasters/notesMaster1.xml", UriKind.Relative), TargetMode.Internal, RtNotesMaster).Id;
                string notesPartSlideRelId = notesPart.CreateRelationship(
                    new Uri($"../slides/slide{i + 1}.xml", UriKind.Relative), TargetMode.Internal, RtSlide).Id;
                WriteContent(notesPart, NotesSlideXml(notes, notesPartMasterRelId, notesPartSlideRelId));
            }
            WriteContent(slidePart, SlideXml(slide, deckTitle, i + 1, slideCount, slideLayoutRelId, slideNotesRelId));
        }
    }

    // -- part XML builders --------------------------------------------------

    private static XElement PresentationXml(int slideCount, string deckTitle, bool includeNotes, string masterRelId, string notesMasterRelId, string[] slideRelIds)
    {
        var sldIdLst = new XElement(P + "sldIdLst");
        for (int i = 1; i <= slideCount; i++)
        {
            sldIdLst.Add(new XElement(P + "sldId",
                new XAttribute("id", 255 + i), new XAttribute(R + "id", slideRelIds[i - 1])));
        }
        var presentation = new XElement(P + "presentation",
            new XAttribute(XNamespace.Xmlns + "a", A), new XAttribute(XNamespace.Xmlns + "r", R), new XAttribute(XNamespace.Xmlns + "p", P),
            new XElement(P + "sldMasterIdLst",
                new XElement(P + "sldMasterId", new XAttribute("id", 2147483648), new XAttribute(R + "id", masterRelId))),
            sldIdLst,
            new XElement(P + "sldSz", new XAttribute("cx", Emu(13.333)), new XAttribute("cy", Emu(7.5)), new XAttribute("type", "screen16x9")),
            new XElement(P + "notesSz", new XAttribute("cx", Emu(8.5)), new XAttribute("cy", Emu(11.0))),
            new XElement(P + "defaultTextStyle", DefaultTextStyle()));
        return presentation;
    }

    private static string LoadTemplate(string name)
    {
        var stream = typeof(PptxWriter).Assembly.GetManifestResourceStream("Office.Automation.OpenXml.Templates." + name)
            ?? throw new InvalidOperationException("missing embedded template: " + name);
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    private static XElement MasterXml(string layoutRelId, string themeRelId)
    {
        _ = themeRelId; // carried in the relationship part, not referenced in XML
        var master = XDocument.Parse(LoadTemplate("slideMaster.xml")).Root!;
        // Trim the template's 11-layout list to the single blank layout we ship.
        var idLst = master.Element(P + "sldLayoutIdLst")!;
        idLst.RemoveNodes();
        idLst.Add(new XElement(P + "sldLayoutId",
            new XAttribute("id", 2147483649), new XAttribute(R + "id", layoutRelId)));
        return master;
    }

    private static XElement LayoutXml(string masterRelId)
    {
        _ = masterRelId; // carried in the relationship part
        return XDocument.Parse(LoadTemplate("slideLayout.xml")).Root!;
    }

    private static XElement NotesMasterXml(string themeRelId)
    {
        _ = themeRelId; // carried in the relationship part
        return XDocument.Parse(LoadTemplate("notesMaster.xml")).Root!;
    }

    private static XElement ThemeXml()
    {
        return XDocument.Parse(LoadTemplate("theme.xml")).Root!;
    }

    private static XElement SlideXml(JsonElement slide, string deckTitle, int pageNumber, int total, string layoutRelId, string notesRelId)
    {
        _ = layoutRelId; // carried in the relationship part
        _ = notesRelId;

        var sld = XDocument.Parse(LoadTemplate("slide.xml")).Root!;
        var spTree = sld.Element(P + "cSld")!.Element(P + "spTree")!;
        var shapes = new List<XElement>();
        string layout = slide.TryGetProperty("semantic_layout", out var l) ? l.GetString() ?? "bullets" : "bullets";
        string title = slide.TryGetProperty("title", out var t) ? t.GetString() ?? "" : "";
        var blocks = slide.TryGetProperty("content_blocks", out var b) ? b : default;

        shapes.Add(Rect(3, 0, 0, Emu(13.333), Emu(7.5), "0F141E"));
        shapes.Add(TextBox(4, Emu(0.9), Emu(7.05), Emu(11.2), Emu(0.3), deckTitle, 10, "9AA7BC", false));
        shapes.Add(TextBox(5, Emu(11.73), Emu(7.0), Emu(1.2), Emu(0.35), $"{pageNumber:00} / {total:00}", 10, "9AA7BC", false, "r"));

        switch (layout)
        {
            case "title_cover":
                shapes.Add(TextBox(6, Emu(1.5), Emu(2.9), Emu(10.3), Emu(1.4), title, 54, "E8ECF2", true, "ctr"));
                if (blocks.ValueKind != JsonValueKind.Undefined)
                {
                    foreach (var block in blocks.EnumerateArray())
                    {
                        if (block.TryGetProperty("type", out var type) && type.GetString() == "text")
                        {
                            var paras = block.GetProperty("paragraphs").EnumerateArray().Select(p => p.GetString() ?? "").ToList();
                            shapes.Add(TextBox(7, Emu(1.5), Emu(4.65), Emu(10.3), Emu(1.0), string.Join("\n", paras), 18, "9AA7BC", false, "ctr"));
                        }
                    }
                }
                break;
            case "bullets":
            default:
                if (title.Length > 0)
                {
                    shapes.Add(TextBox(6, Emu(0.9), Emu(0.55), Emu(11.5), Emu(0.75), title, 28, "E8ECF2", true));
                    shapes.Add(Rect(7, Emu(0.9), Emu(1.42), Emu(0.9), Emu(0.05), "4D9DE0"));
                }
                int row = 0;
                if (blocks.ValueKind != JsonValueKind.Undefined)
                {
                    foreach (var block in blocks.EnumerateArray())
                    {
                        if (block.TryGetProperty("type", out var type) && type.GetString() == "bullets")
                        {
                            foreach (var item in block.GetProperty("items").EnumerateArray())
                            {
                                double y = 1.78 + row * 1.02;
                                shapes.Add(Oval(100 + row, Emu(0.95), Emu(y + 0.17), Emu(0.18), Emu(0.18), "7FC8A9"));
                                shapes.Add(TextBox(200 + row, Emu(1.35), Emu(y), Emu(10.9), Emu(0.9), item.GetString() ?? "", 16.5, "E8ECF2", false));
                                row++;
                            }
                        }
                    }
                }
                break;
        }

        foreach (var shape in shapes)
        {
            spTree.Add(shape);
        }
        return sld;
    }

    private static XElement NotesSlideXml(string notes, string notesMasterRelId, string slideRelId)
    {
        _ = notesMasterRelId;
        _ = slideRelId;

        var notesSlide = XDocument.Parse(LoadTemplate("notesSlide.xml")).Root!;
        var textElements = notesSlide.Descendants(A + "t").ToList();
        if (textElements.Count > 0)
        {
            textElements[0].Value = notes;
        }
        return notesSlide;
    }

    // -- shape builders -----------------------------------------------------

    private static XElement ClrMap() =>
        new XElement(P + "clrMap",
            new XAttribute("bg1", "lt1"), new XAttribute("tx1", "dk1"), new XAttribute("bg2", "lt2"), new XAttribute("tx2", "dk2"),
            new XAttribute("accent1", "accent1"), new XAttribute("accent2", "accent2"), new XAttribute("accent3", "accent3"),
            new XAttribute("accent4", "accent4"), new XAttribute("accent5", "accent5"), new XAttribute("accent6", "accent6"),
            new XAttribute("hlink", "hlink"), new XAttribute("folHlink", "folHlink"));

    private static XElement Rect(int id, long x, long y, long cx, long cy, string fill)
    {
        var spPr = new XElement(P + "spPr",
            new XElement(A + "xfrm", new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)), new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy))),
            new XElement(A + "prstGeom", new XAttribute("prst", "rect"), new XElement(A + "avLst")),
            new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", fill))),
            new XElement(A + "ln", new XElement(A + "noFill")));
        return new XElement(P + "sp", NonVisualProps(id, null, "Background", textBox: false), spPr, Style(), EmptyTxBody());
    }

    private static XElement Oval(int id, long x, long y, long cx, long cy, string fill)
    {
        var spPr = new XElement(P + "spPr",
            new XElement(A + "xfrm", new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)), new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy))),
            new XElement(A + "prstGeom", new XAttribute("prst", "ellipse"), new XElement(A + "avLst")),
            new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", fill))),
            new XElement(A + "ln", new XElement(A + "noFill")));
        return new XElement(P + "sp", NonVisualProps(id, null, "Oval", textBox: false), spPr, Style(), EmptyTxBody());
    }

    private static XElement TextBox(int id, long x, long y, long cx, long cy, string text, double sizePt, string colorHex, bool bold, string align = "l")
    {
        var spPr = new XElement(P + "spPr",
            new XElement(A + "xfrm", new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)), new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy))),
            new XElement(A + "prstGeom", new XAttribute("prst", "rect"), new XElement(A + "avLst")),
            new XElement(A + "noFill"));
        var txBody = new XElement(P + "txBody",
            new XElement(A + "bodyPr", new XAttribute("wrap", "square")),
            new XElement(A + "lstStyle"));
        string alignVal = align switch { "ctr" => "ctr", "r" => "r", _ => "l" };
        foreach (var line in text.Split('\n'))
        {
            var para = new XElement(A + "p", new XAttribute("algn", alignVal));
            var run = new XElement(A + "r",
                new XElement(A + "rPr",
                    new XAttribute("lang", "zh-CN"),
                    new XAttribute("sz", (int)(sizePt * 100)),
                    bold ? new XAttribute("b", "1") : null,
                    new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", colorHex))),
                    new XElement(A + "latin", new XAttribute("typeface", "Segoe UI")),
                    new XElement(A + "ea", new XAttribute("typeface", "Microsoft YaHei")),
                    new XElement(A + "cs", new XAttribute("typeface", "Segoe UI"))),
                new XElement(A + "t", line));
            para.Add(run);
            txBody.Add(para);
        }
        return new XElement(P + "sp", NonVisualProps(id, null, "TextBox", textBox: true), spPr, Style(), txBody);
    }

    private static XElement NonVisualProps(int id, string? placeholderType, string name, bool textBox = false)
    {
        var cNvSpPr = new XElement(P + "cNvSpPr");
        if (textBox)
        {
            cNvSpPr.Add(new XAttribute("txBox", "1"));
        }
        var nvSpPr = new XElement(P + "nvSpPr",
            new XElement(P + "cNvPr", new XAttribute("id", id), new XAttribute("name", name + " " + id)),
            cNvSpPr,
            new XElement(P + "nvPr"));
        if (placeholderType is not null)
        {
            var ph = new XElement(P + "ph", new XAttribute("type", placeholderType));
            if (placeholderType == "body")
            {
                ph.Add(new XAttribute("idx", "1"));
            }
            nvSpPr.Element(P + "nvPr")!.Add(ph);
        }
        return nvSpPr;
    }

    private static XElement BuildSpTree(params XElement[] children)
    {
        var spTree = new XElement(P + "spTree");
        spTree.Add(children);
        return spTree;
    }

    private static XElement[] GroupShapeProps(string id, long x, long y, long cx, long cy) =>
        new[]
        {
            new XElement(P + "nvGrpSpPr",
                new XElement(P + "cNvPr", new XAttribute("id", id), new XAttribute("name", "")),
                new XElement(P + "cNvGrpSpPr"),
                new XElement(P + "nvPr")),
            new XElement(P + "grpSpPr",
                new XElement(A + "xfrm",
                    new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)),
                    new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy)),
                    new XElement(A + "chOff", new XAttribute("x", 0), new XAttribute("y", 0)),
                    new XElement(A + "chExt", new XAttribute("cx", cx), new XAttribute("cy", cy)))),
        };

    private static XElement EmptyTxBody() => new XElement(P + "txBody",
        new XElement(A + "bodyPr", new XAttribute("rtlCol", "0"), new XAttribute("anchor", "ctr")),
        new XElement(A + "lstStyle"),
        new XElement(A + "p"));

    /// <summary>Required p:style block every sp in a slide carries.</summary>
    private static XElement Style() =>
        new XElement(P + "style",
            new XElement(A + "lnRef", new XAttribute("idx", "1"), new XElement(A + "schemeClr", new XAttribute("val", "accent1"))),
            new XElement(A + "fillRef", new XAttribute("idx", "3"), new XElement(A + "schemeClr", new XAttribute("val", "accent1"))),
            new XElement(A + "effectRef", new XAttribute("idx", "2"), new XElement(A + "schemeClr", new XAttribute("val", "accent1"))),
            new XElement(A + "fontRef", new XAttribute("idx", "minor"), new XElement(A + "schemeClr", new XAttribute("val", "lt1"))));

    private static XElement[] StyleLevels(int sizeCentipoints) =>
        Enumerable.Range(1, 9)
            .Select(level => new XElement(A + $"lvl{level}pPr",
                new XElement(A + "defRPr", new XAttribute("sz", sizeCentipoints * 100))))
            .ToArray();

    private static XElement[] DefaultTextStyle() =>
        Enumerable.Range(1, 9)
            .Select(level => new XElement(A + $"lvl{level}pPr",
                new XElement(A + "defRPr", new XAttribute("sz", 1800))))
            .ToArray();

    private static XElement EffectStyle() =>
        new XElement(A + "effectStyle",
            new XElement(A + "effectLst",
                new XElement(A + "outerShdw",
                    new XAttribute("blurRad", "0"), new XAttribute("dist", "0"), new XAttribute("dir", "5400000"), new XAttribute("rotWithShape", "0"),
                    new XElement(A + "srgbClr", new XAttribute("val", "000000")),
                    new XElement(A + "alpha", new XAttribute("val", "0")))));

    private static XElement[] FillStyleList() =>
        new[]
        {
            new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr"))),
            new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr"))),
            new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr"))),
        };

    private static XElement[] LineStyleList() =>
        new[]
        {
            new XElement(A + "ln", new XAttribute("w", "9525"), new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr")))),
            new XElement(A + "ln", new XAttribute("w", "9525"), new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr")))),
            new XElement(A + "ln", new XAttribute("w", "9525"), new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr")))),
        };

    private static long Emu(double inches) => (long)Math.Round(inches * EmuPerInch);

    private static PackagePart CreatePart(Package package, string uri, string contentType) =>
        package.CreatePart(new Uri(uri, UriKind.Relative), contentType, CompressionOption.Maximum);

    private static void WriteContent(PackagePart part, XElement content)
    {
        using var stream = part.GetStream();
        content.Save(stream);
    }
}
