using System.IO.Packaging;
using System.Text.Json;
using System.Xml.Linq;

namespace Office.Automation.OpenXml;

/// <summary>
/// Self-implemented PPTX writer — zero NuGet dependencies.
///
/// OOXML via in-box System.IO.Packaging + LINQ to XML (dependency policy
/// 2026-08-16). System.IO.Packaging OWNS [Content_Types].xml and every
/// .rels part: register content types at CreatePart and create
/// relationships through CreateRelationship — never hand-write those parts.
/// </summary>
public static class PptxWriter
{
    private static readonly XNamespace A = "http://schemas.openxmlformats.org/drawingml/2006/main";
    private static readonly XNamespace P = "http://schemas.openxmlformats.org/presentationml/2006/main";
    private static readonly XNamespace R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";

    private const string RtSlideLayout = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout";
    private const string RtSlideMaster = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster";
    private const string RtTheme = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme";
    private const string RtNotesSlide = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide";
    private const string RtNotesMaster = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesMaster";
    private const string RtSlide = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide";
    private const string RtOfficeDocument = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument";

    private const string CtRels = "application/vnd.openxmlformats-package.relationships+xml";
    private const string CtPresentation = "application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml";
    private const string CtSlide = "application/vnd.openxmlformats-officedocument.presentationml.slide+xml";
    private const string CtSlideLayout = "application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml";
    private const string CtSlideMaster = "application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml";
    private const string CtNotesSlide = "application/vnd.openxmlformats-officedocument.presentationml.notesSlide+xml";
    private const string CtNotesMaster = "application/vnd.openxmlformats-officedocument.presentationml.notesMaster+xml";
    private const string CtTheme = "application/vnd.openxmlformats-officedocument.theme+xml";
    private const string CtPng = "image/png";
    private const string CtJpeg = "image/jpeg";
    private const string RtImage = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/image";

    private const long EmuPerInch = 914400;

    /// <summary>Compile a Deck IR JSON file into a PPTX package.</summary>
    public static void CompileDeck(
        string irPath,
        string outPath,
        PresentationTemplatePackage? templatePackage = null)
    {
        PresentationTemplatePackage activeTemplate =
            templatePackage ?? PresentationTemplatePackage.EmbeddedDefault();
        using var doc = JsonDocument.Parse(File.ReadAllText(irPath));
        var slides = doc.RootElement.GetProperty("document").GetProperty("slides");
        int slideCount = slides.GetArrayLength();
        string deckTitle = "Deck";
        if (doc.RootElement.TryGetProperty("metadata", out var meta) && meta.TryGetProperty("title", out var title))
        {
            deckTitle = title.GetString() ?? deckTitle;
        }
        const bool includeNotes = true;
        string irDirectory = Path.GetDirectoryName(Path.GetFullPath(irPath)) ?? ".";
        using var package = Package.Open(outPath, FileMode.Create);
        // Package-level relationship (managed by Packaging; its id is
        // auto-generated and referenced by nothing in our XML).
        package.CreateRelationship(
            new Uri("/ppt/presentation.xml", UriKind.Relative), TargetMode.Internal, RtOfficeDocument);

        // Relationship ids are auto-generated by Packaging: create the
        // relationship first, then write XML referencing the returned id.
        var presentationPart = CreatePart(package, "/ppt/presentation.xml", CtPresentation);
        string masterRelId = presentationPart.CreateRelationship(
            new Uri("slideMasters/slideMaster1.xml", UriKind.Relative), TargetMode.Internal, RtSlideMaster).Id;
        string notesMasterRelId = "";
        var mediaParts = new Dictionary<string, PackagePart>();
        var mediaCounter = 0;
        PackagePart? logoPart = null;
        if (activeTemplate.Logo is not null)
        {
            logoPart = CreatePart(package, "/ppt/media/logo-light.png", CtPng);
            using var logoStream = logoPart.GetStream();
            logoStream.Write(activeTemplate.Logo);
        }

        var slideRelIds = new string[slideCount];
        for (int i = 0; i < slideCount; i++)
        {
            slideRelIds[i] = presentationPart.CreateRelationship(
                new Uri($"slides/slide{i + 1}.xml", UriKind.Relative), TargetMode.Internal, RtSlide).Id;
        }
        WriteContent(presentationPart, PresentationXml(slideCount, deckTitle, includeNotes, masterRelId, notesMasterRelId, slideRelIds));

        var masterPart = CreatePart(package, "/ppt/slideMasters/slideMaster1.xml", CtSlideMaster);
        string masterLayoutRelId = masterPart.CreateRelationship(
            new Uri("../slideLayouts/slideLayout1.xml", UriKind.Relative), TargetMode.Internal, RtSlideLayout).Id;
        string masterThemeRelId = masterPart.CreateRelationship(
            new Uri("../theme/theme1.xml", UriKind.Relative), TargetMode.Internal, RtTheme).Id;
        WriteContent(masterPart, MasterXml(masterLayoutRelId, masterThemeRelId, activeTemplate));

        var layoutPart = CreatePart(package, "/ppt/slideLayouts/slideLayout1.xml", CtSlideLayout);
        string layoutMasterRelId = layoutPart.CreateRelationship(
            new Uri("../slideMasters/slideMaster1.xml", UriKind.Relative), TargetMode.Internal, RtSlideMaster).Id;
        WriteContent(layoutPart, LayoutXml(layoutMasterRelId, activeTemplate));

        var themePart = CreatePart(package, "/ppt/theme/theme1.xml", CtTheme);
        WriteContent(themePart, ThemeXml(activeTemplate));

        if (includeNotes)
        {
            var notesMasterPart = CreatePart(package, "/ppt/notesMasters/notesMaster1.xml", CtNotesMaster);
            string notesMasterThemeRelId = notesMasterPart.CreateRelationship(
                new Uri("../theme/theme1.xml", UriKind.Relative), TargetMode.Internal, RtTheme).Id;
            WriteContent(notesMasterPart, NotesMasterXml(notesMasterThemeRelId, activeTemplate));
        }

        for (int i = 0; i < slideCount; i++)
        {
            var slide = slides[i];
            string notes = slide.TryGetProperty("speaker_notes", out var n) ? n.GetString() ?? "" : "";
            string semanticLayout = slide.TryGetProperty("semantic_layout", out var sl)
                ? sl.GetString() ?? "bullets"
                : "bullets";
            string layout = activeTemplate.ResolveRenderer(semanticLayout);
            var slidePart = CreatePart(package, $"/ppt/slides/slide{i + 1}.xml", CtSlide);
            string slideLayoutRelId = slidePart.CreateRelationship(
                new Uri("../slideLayouts/slideLayout1.xml", UriKind.Relative), TargetMode.Internal, RtSlideLayout).Id;
            string slideNotesRelId = "";
            if (includeNotes)
            {
                slideNotesRelId = slidePart.CreateRelationship(
                    new Uri($"../notesSlides/notesSlide{i + 1}.xml", UriKind.Relative), TargetMode.Internal, RtNotesSlide).Id;
                var notesPart = CreatePart(package, $"/ppt/notesSlides/notesSlide{i + 1}.xml", CtNotesSlide);
                string notesPartMasterRelId = notesPart.CreateRelationship(
                    new Uri("../notesMasters/notesMaster1.xml", UriKind.Relative), TargetMode.Internal, RtNotesMaster).Id;
                string notesPartSlideRelId = notesPart.CreateRelationship(
                    new Uri($"../slides/slide{i + 1}.xml", UriKind.Relative), TargetMode.Internal, RtSlide).Id;
                WriteContent(
                    notesPart,
                    NotesSlideXml(
                        notes,
                        notesPartMasterRelId,
                        notesPartSlideRelId,
                        activeTemplate));
            }
            // Slide images → media parts (cached per path) + rels.
            var imageRelIds = new Dictionary<string, string>();
            if (slide.TryGetProperty("images", out var images))
            {
                foreach (var image in images.EnumerateArray())
                {
                    string uri = image.TryGetProperty("uri", out var u) ? u.GetString() ?? "" : "";
                    if (uri.Length == 0)
                    {
                        continue;
                    }
                    string full = ResolveMediaPath(uri, irDirectory);
                    if (!mediaParts.TryGetValue(full, out var mediaPart) && File.Exists(full))
                    {
                        mediaCounter++;
                        (string extension, string contentType) = ImagePartFormat(full);
                        mediaPart = CreatePart(
                            package,
                            $"/ppt/media/image{mediaCounter}{extension}",
                            contentType);
                        using (var source = File.OpenRead(full))
                        using (var target = mediaPart.GetStream())
                        {
                            source.CopyTo(target);
                        }
                        mediaParts[full] = mediaPart;
                    }
                    if (mediaPart is not null)
                    {
                        string relId = slidePart.CreateRelationship(mediaPart.Uri, TargetMode.Internal, RtImage).Id;
                        // Key by both the raw IR uri (layouts look up the raw
                        // value) and the resolved full path.
                        imageRelIds[full] = relId;
                        imageRelIds[uri] = relId;
                    }
                }
            }

            // Brand logo for cover/closing slides.
            string? logoRelId = null;
            if (logoPart is not null && (layout == "title_cover" || layout == "closing"))
            {
                logoRelId = slidePart.CreateRelationship(logoPart.Uri, TargetMode.Internal, RtImage).Id;
            }

            WriteContent(
                slidePart,
                SlideXml(
                    slide,
                    deckTitle,
                    i + 1,
                    slideCount,
                    slideLayoutRelId,
                    slideNotesRelId,
                    imageRelIds,
                    logoRelId,
                    irDirectory,
                    activeTemplate));
        }
    }

    private static string ResolveMediaPath(string uri, string irDirectory)
    {
        var direct = Path.GetFullPath(uri, irDirectory);
        if (File.Exists(direct))
        {
            return direct;
        }
        var fromCwd = Path.GetFullPath(uri);
        return File.Exists(fromCwd) ? fromCwd : direct;
    }

    private static (string Extension, string ContentType) ImagePartFormat(string path) =>
        Path.GetExtension(path).ToLowerInvariant() switch
        {
            ".jpg" or ".jpeg" => (".jpg", CtJpeg),
            ".png" => (".png", CtPng),
            string extension => throw new InvalidDataException(
                $"presentation image '{path}' uses unsupported format '{extension}'; expected PNG or JPEG"),
        };

    // -- part XML builders --------------------------------------------------

    private static XElement PresentationXml(int slideCount, string deckTitle, bool includeNotes, string masterRelId, string notesMasterRelId, string[] slideRelIds)
    {
        var sldIdLst = new XElement(P + "sldIdLst");
        for (int i = 1; i <= slideCount; i++)
        {
            sldIdLst.Add(new XElement(P + "sldId",
                new XAttribute("id", 255 + i), new XAttribute(R + "id", slideRelIds[i - 1])));
        }
        var presentation = new XElement(P + "presentation",
            new XAttribute(XNamespace.Xmlns + "a", A), new XAttribute(XNamespace.Xmlns + "r", R), new XAttribute(XNamespace.Xmlns + "p", P),
            new XElement(P + "sldMasterIdLst",
                new XElement(P + "sldMasterId", new XAttribute("id", 2147483648), new XAttribute(R + "id", masterRelId))),
            sldIdLst,
            new XElement(P + "sldSz", new XAttribute("cx", Emu(13.333)), new XAttribute("cy", Emu(7.5)), new XAttribute("type", "screen16x9")),
            new XElement(P + "notesSz", new XAttribute("cx", Emu(8.5)), new XAttribute("cy", Emu(11.0))),
            new XElement(P + "defaultTextStyle", DefaultTextStyle()));
        return presentation;
    }

    private static XElement MasterXml(
        string layoutRelId,
        string themeRelId,
        PresentationTemplatePackage template)
    {
        _ = themeRelId; // carried in the relationship part, not referenced in XML
        var master = XDocument.Parse(template.Part("slide_master")).Root!;
        // Trim the template's 11-layout list to the single blank layout we ship.
        var idLst = master.Element(P + "sldLayoutIdLst")!;
        idLst.RemoveNodes();
        idLst.Add(new XElement(P + "sldLayoutId",
            new XAttribute("id", 2147483649), new XAttribute(R + "id", layoutRelId)));
        return master;
    }

    private static XElement LayoutXml(
        string masterRelId,
        PresentationTemplatePackage template)
    {
        _ = masterRelId; // carried in the relationship part
        return XDocument.Parse(template.Part("slide_layout")).Root!;
    }

    private static XElement NotesMasterXml(
        string themeRelId,
        PresentationTemplatePackage template)
    {
        _ = themeRelId; // carried in the relationship part
        return XDocument.Parse(template.Part("notes_master")).Root!;
    }

    private static XElement ThemeXml(PresentationTemplatePackage template)
    {
        return XDocument.Parse(template.Part("theme")).Root!;
    }

    private static XElement SlideXml(
        JsonElement slide,
        string deckTitle,
        int pageNumber,
        int total,
        string layoutRelId,
        string notesRelId,
        Dictionary<string, string> imageRelIds,
        string? logoRelId,
        string irDirectory,
        PresentationTemplatePackage template)
    {
        _ = layoutRelId;
        _ = notesRelId;
        _ = irDirectory;

        var sld = XDocument.Parse(template.Part("slide")).Root!;
        var spTree = sld.Element(P + "cSld")!.Element(P + "spTree")!;
        var shapes = new List<XElement>();
        string semanticLayout = slide.TryGetProperty("semantic_layout", out var l)
            ? l.GetString() ?? "bullets"
            : "bullets";
        string layout = template.ResolveRenderer(semanticLayout);
        string title = slide.TryGetProperty("title", out var t) ? t.GetString() ?? "" : "";
        var blocks = slide.TryGetProperty("content_blocks", out var b) ? b : default;
        var images = slide.TryGetProperty("images", out var imgs) ? imgs : default;

        switch (layout)
        {
            case "title_cover":
                TitleCover(shapes, title, deckTitle, logoRelId, blocks, images, imageRelIds);
                break;
            case "section_cover":
                SectionCover(shapes, title, blocks);
                break;
            case "two_columns":
                ContentHeader(shapes, title);
                TwoColumns(shapes, blocks);
                break;
            case "comparison":
                ContentHeader(shapes, title);
                Comparison(shapes, blocks);
                break;
            case "timeline":
                ContentHeader(shapes, title);
                Timeline(shapes, blocks);
                break;
            case "kpi_dashboard":
                ContentHeader(shapes, title);
                KpiDashboard(shapes, blocks);
                break;
            case "technical_architecture":
                ContentHeader(shapes, title);
                TechnicalArchitecture(shapes, blocks);
                break;
            case "image_left_text_right":
                ContentHeader(shapes, title);
                ImageLeftTextRight(shapes, blocks, imageRelIds, title);
                break;
            case "image_grid":
                ContentHeader(shapes, title);
                ImageGrid(shapes, images, imageRelIds);
                break;
            case "closing":
                Closing(shapes, title, blocks, logoRelId);
                break;
            case "bullets":
            default:
                ContentHeader(shapes, title);
                Bullets(shapes, blocks);
                break;
        }

        foreach (var shape in shapes)
        {
            spTree.Add(shape);
        }
        ApplyTemplateStyle(sld, template);
        return sld;
    }

    private static void ContentHeader(List<XElement> shapes, string title)
    {
        if (title.Length > 0)
        {
            double titleSize = title.Length > 52 ? 31 : 36;
            shapes.Add(TextBox(6, Emu(0.9), Emu(0.34), Emu(11.5), Emu(1.08), title, titleSize, C_TEXT, true, displayFont: true));
            shapes.Add(Rect(7, Emu(0.9), Emu(1.48), Emu(0.72), Emu(0.06), C_ACCENT));
            shapes.Add(Rect(8, Emu(1.72), Emu(1.48), Emu(10.68), Emu(0.015), C_GHOST));
        }
    }

    private static void TitleCover(
        List<XElement> shapes,
        string title,
        string deckTitle,
        string? logoRelId,
        JsonElement blocks,
        JsonElement images,
        Dictionary<string, string> imageRelIds)
    {
        string? hero = FirstImageUri(images);
        if (hero is not null && imageRelIds.TryGetValue(hero, out string? heroRelId))
        {
            shapes.Add(Pic(3, heroRelId, 0, 0, Emu(13.333), Emu(7.5), title));
            shapes.Add(Rect(4, 0, 0, Emu(6.15), Emu(7.5), C_BG));
        }
        else
        {
            shapes.Add(Rect(3, 0, 0, Emu(13.333), Emu(7.5), C_BG));
            shapes.Add(GhostCircle(Emu(9.7), Emu(-0.65), Emu(4.4), Emu(4.4)));
            shapes.Add(GhostCircle(Emu(10.6), Emu(4.85), Emu(3.4), Emu(3.4)));
        }
        shapes.Add(Rect(10, Emu(0.78), Emu(1.15), Emu(0.1), Emu(4.95), C_ACCENT));
        if (logoRelId is not null)
        {
            shapes.Add(Pic(11, logoRelId, Emu(1.0), Emu(0.62), Emu(0.8), Emu(0.45), "DCC-MCP logo"));
        }
        shapes.Add(TextBox(12, Emu(1.02), Emu(1.42), Emu(4.85), Emu(0.38), "GOVERNED OFFICE AUTOMATION", 12, C_ACCENT, true));
        shapes.Add(TextBox(13, Emu(1.0), Emu(2.0), Emu(4.95), Emu(2.18), title, 50, C_TEXT, true, displayFont: true));
        if (blocks.ValueKind != JsonValueKind.Undefined)
        {
            foreach (var block in blocks.EnumerateArray())
            {
                if (block.TryGetProperty("type", out var type) && type.GetString() == "text")
                {
                    var paras = block.GetProperty("paragraphs").EnumerateArray().Select(p => p.GetString() ?? "").ToList();
                    shapes.Add(TextBox(14, Emu(1.02), Emu(4.42), Emu(4.72), Emu(1.1), string.Join("\n", paras), 18, C_MUTED, false));
                }
            }
        }
        shapes.Add(TextBox(15, Emu(1.02), Emu(6.68), Emu(4.8), Emu(0.35), deckTitle + "  /  dcc-mcp", 10.5, C_MUTED, false));
    }

    private static void SectionCover(List<XElement> shapes, string title, JsonElement blocks)
    {
        shapes.Add(Rect(3, 0, 0, Emu(13.333), Emu(7.5), C_BG_SOFT));
        shapes.Add(GhostCircle(Emu(10.5), Emu(0.35), Emu(2.7), Emu(2.7)));
        string number = "";
        string clean = title;
        var m = System.Text.RegularExpressions.Regex.Match(title, @"^(\d+)\s*[·.:]\s*(.*)$");
        if (m.Success)
        {
            number = m.Groups[1].Value;
            clean = m.Groups[2].Value;
        }
        if (number.Length > 0)
        {
            shapes.Add(TextBox(4, Emu(0.7), Emu(0.7), Emu(5.0), Emu(4.2), number, 200, C_GHOST, true));
        }
        shapes.Add(Rect(5, Emu(0.9), Emu(3.05), Emu(0.18), Emu(1.2), C_ACCENT_2));
        shapes.Add(TextBox(6, Emu(1.3), Emu(3.0), Emu(11.0), Emu(1.4), clean, 44, C_TEXT, true, displayFont: true));
        if (blocks.ValueKind != JsonValueKind.Undefined)
        {
            foreach (var block in blocks.EnumerateArray())
            {
                if (block.TryGetProperty("type", out var type) && type.GetString() == "text")
                {
                    var paras = block.GetProperty("paragraphs").EnumerateArray().Select(p => p.GetString() ?? "").ToList();
                    shapes.Add(TextBox(7, Emu(1.35), Emu(4.5), Emu(10.5), Emu(0.6), string.Join("\n", paras), 15, C_MUTED, false));
                }
            }
        }
    }

    private static void Bullets(List<XElement> shapes, JsonElement blocks)
    {
        if (blocks.ValueKind == JsonValueKind.Undefined)
        {
            return;
        }
        int id = 100;
        double y = 1.78;
        foreach (var block in blocks.EnumerateArray())
        {
            if (block.TryGetProperty("type", out var type) && type.GetString() == "bullets")
            {
                var items = block.GetProperty("items").EnumerateArray().Select(i => i.GetString() ?? "").ToList();
                for (int i = 0; i < items.Count; i++)
                {
                    shapes.Add(Oval(id++, Emu(0.95), Emu(y + 0.17), Emu(0.18), Emu(0.18), C_ACCENT_2));
                    shapes.Add(TextBox(id++, Emu(1.35), Emu(y), Emu(10.9), Emu(0.9), items[i], 16.5, C_TEXT, false));
                    if (i < items.Count - 1)
                    {
                        shapes.Add(Rect(id++, Emu(0.9), Emu(y + 0.95), Emu(11.5), Emu(0.017), C_GHOST));
                    }
                    y += 1.02;
                }
            }
        }
    }

    private static void TwoColumns(List<XElement> shapes, JsonElement blocks)
    {
        var texts = BulletBlocks(blocks);
        for (int col = 0; col < Math.Min(2, texts.Count); col++)
        {
            double left = 0.9 + col * 6.0;
            var items = texts[col];
            string color = col == 0 ? C_ACCENT : C_ACCENT_2;
            var head = RoundRect(200 + col * 20, Emu(left), Emu(1.78), Emu(5.6), Emu(0.62), color, 0.16);
            FillShapeText(head, items.Count > 0 ? items[0] : "", 16, C_TEXT, true, "l");
            shapes.Add(head);
            var body = RoundRect(201 + col * 20, Emu(left), Emu(2.52), Emu(5.6), Emu(4.1), C_PANEL, 0.05);
            FillShapeText(body, string.Join("\n", items.Skip(1).Select(i => "●  " + i)), 14.5, C_TEXT, false, "l");
            shapes.Add(body);
        }
    }

    private static void Comparison(List<XElement> shapes, JsonElement blocks)
    {
        var texts = BulletBlocks(blocks);
        for (int col = 0; col < Math.Min(2, texts.Count); col++)
        {
            double left = 0.9 + col * 6.0;
            var items = texts[col];
            string color = col == 0 ? C_ACCENT : C_ACCENT_2;
            shapes.Add(Rect(240 + col * 20, Emu(left), Emu(1.82), Emu(5.6), Emu(4.78), col == 0 ? C_BG_SOFT : C_PANEL));
            shapes.Add(TextBox(241 + col * 20, Emu(left + 0.38), Emu(2.05), Emu(0.95), Emu(0.62), $"0{col + 1}", 28, color, true, displayFont: true));
            shapes.Add(TextBox(242 + col * 20, Emu(left + 1.36), Emu(2.08), Emu(3.8), Emu(0.58), items.Count > 0 ? items[0] : "", 24, C_TEXT, true, displayFont: true));
            double top = 3.05;
            for (int i = 1; i < items.Count; i++)
            {
                shapes.Add(Oval(243 + col * 20 + i * 2, Emu(left + 0.42), Emu(top + 0.17), Emu(0.14), Emu(0.14), color));
                shapes.Add(TextBox(244 + col * 20 + i * 2, Emu(left + 0.76), Emu(top), Emu(4.35), Emu(0.75), items[i], 17, C_TEXT, false));
                top += 0.9;
            }
        }
    }

    private static void Timeline(List<XElement> shapes, JsonElement blocks)
    {
        var items = FirstBulletItems(blocks);
        int n = Math.Max(1, items.Count);
        double step = 11.5 / n;
        double labelW = Math.Min(3.6, Math.Max(step - 0.3, 1.0));
        shapes.Add(Rect(300, Emu(0.9), Emu(3.55), Emu(11.5), Emu(0.04), C_ACCENT));
        for (int i = 0; i < items.Count; i++)
        {
            double x = 0.9 + step * i + step / 2;
            shapes.Add(OvalOutlined(301 + i * 2, Emu(x - 0.17), Emu(3.38), Emu(0.34), Emu(0.34), C_ACCENT_2, (i + 1).ToString()));
            double labelY = i % 2 == 0 ? 2.3 : 3.9;
            shapes.Add(TextBox(302 + i * 2, Emu(x - labelW / 2), Emu(labelY), Emu(labelW), Emu(1.05), items[i], 13.5, C_TEXT, false, "ctr"));
        }
    }

    private static void KpiDashboard(List<XElement> shapes, JsonElement blocks)
    {
        var items = FirstBulletItems(blocks);
        for (int i = 0; i < Math.Min(6, items.Count); i++)
        {
            int row = i / 3;
            int col = i % 3;
            double left = 0.9 + col * 3.85;
            double top = 1.82 + row * 2.3;
            var parts = items[i].Split('|', 2);
            string value = parts[0].Trim();
            string label = parts.Length > 1 ? parts[1].Trim() : "";
            string color = i % 2 == 0 ? C_ACCENT : C_ACCENT_2;
            shapes.Add(Rect(400 + i * 4, Emu(left), Emu(top), Emu(0.1), Emu(1.72), color));
            shapes.Add(TextBox(401 + i * 4, Emu(left + 0.3), Emu(top - 0.02), Emu(2.9), Emu(0.92), value, 46, C_TEXT, true, displayFont: true));
            shapes.Add(TextBox(402 + i * 4, Emu(left + 0.32), Emu(top + 0.94), Emu(2.95), Emu(0.7), label, 16, C_MUTED, false));
            if (col < 2)
            {
                shapes.Add(Rect(403 + i * 4, Emu(left + 3.48), Emu(top + 0.12), Emu(0.015), Emu(1.42), C_GHOST));
            }
        }
    }

    private static void TechnicalArchitecture(List<XElement> shapes, JsonElement blocks)
    {
        var items = FirstBulletItems(blocks);
        double top = 1.83;
        var centers = new List<double>();
        for (int i = 0; i < items.Count; i++)
        {
            var chip = OvalOutlined(500 + i, Emu(2.35), Emu(top + 0.16), Emu(0.42), Emu(0.42), C_ACCENT, (i + 1).ToString());
            shapes.Add(chip);
            var box = RoundRect(520 + i, Emu(3.05), Emu(top), Emu(9.35), Emu(0.78), C_PANEL, 0.1);
            FillShapeText(box, items[i], 14.5, C_TEXT, false, "l");
            shapes.Add(box);
            centers.Add(top + 0.39);
            top += 0.95;
        }
        if (centers.Count >= 2)
        {
            shapes.Add(Connector(600, Emu(2.56), Emu(centers[0] + 0.18), Emu(2.56), Emu(centers[^1] + 0.18), C_ACCENT));
        }
    }

    private static void ImageLeftTextRight(List<XElement> shapes, JsonElement blocks, Dictionary<string, string> imageRelIds, string title)
    {
        if (blocks.ValueKind == JsonValueKind.Undefined)
        {
            return;
        }
        string? imagePath = null;
        var bullets = new List<string>();
        foreach (var block in blocks.EnumerateArray())
        {
            if (block.TryGetProperty("type", out var type))
            {
                if (type.GetString() == "image" && block.TryGetProperty("resource", out var res))
                {
                    imagePath = res.GetString();
                }
                else if (type.GetString() == "bullets" && block.TryGetProperty("items", out var its))
                {
                    bullets = its.EnumerateArray().Select(i => i.GetString() ?? "").ToList();
                }
            }
        }
        int id = 700;
        if (imagePath is not null && imageRelIds.TryGetValue(imagePath, out var relId))
        {
            shapes.Add(Pic(id++, relId, Emu(0.9), Emu(1.78), Emu(7.15), Emu(4.82), title));
        }
        else if (imagePath is not null)
        {
            shapes.Add(TextBox(id++, Emu(0.9), Emu(1.78), Emu(7.15), Emu(0.5), "missing_asset: " + imagePath, 11, C_MUTED, false));
        }
        if (bullets.Count > 0)
        {
            double top = 1.92;
            for (int i = 0; i < Math.Min(4, bullets.Count); i++)
            {
                string color = i % 2 == 0 ? C_ACCENT : C_ACCENT_2;
                shapes.Add(TextBox(id++, Emu(8.4), Emu(top), Emu(0.66), Emu(0.48), $"0{i + 1}", 18, color, true, displayFont: true));
                shapes.Add(TextBox(id++, Emu(9.18), Emu(top - 0.02), Emu(3.15), Emu(0.9), bullets[i], 16, C_TEXT, false));
                if (i < Math.Min(4, bullets.Count) - 1)
                {
                    shapes.Add(Rect(id++, Emu(8.4), Emu(top + 0.94), Emu(3.92), Emu(0.015), C_GHOST));
                }
                top += 1.12;
            }
        }
    }

    private static void ImageGrid(List<XElement> shapes, JsonElement images, Dictionary<string, string> imageRelIds)
    {
        if (images.ValueKind == JsonValueKind.Undefined)
        {
            return;
        }
        var cards = new List<(string Id, string Uri)>();
        foreach (var image in images.EnumerateArray())
        {
            string id = image.TryGetProperty("id", out var i) ? i.GetString() ?? "" : "";
            string uri = image.TryGetProperty("uri", out var u) ? u.GetString() ?? "" : "";
            if (uri.Length > 0)
            {
                cards.Add((id, uri));
            }
        }
        if (cards.Count == 0)
        {
            return;
        }
        if (cards.Count == 3)
        {
            AddImageTile(shapes, 800, cards[0], imageRelIds, 0.9, 1.78, 7.35, 4.88);
            AddImageTile(shapes, 810, cards[1], imageRelIds, 8.55, 1.78, 3.85, 2.28);
            AddImageTile(shapes, 820, cards[2], imageRelIds, 8.55, 4.32, 3.85, 2.34);
            return;
        }
        int cols = cards.Count >= 8 ? 4 : 2;
        double gap = 0.25;
        double cardW = (11.5 - gap * (cols - 1)) / cols;
        int rows = (cards.Count + cols - 1) / cols;
        double cardH = Math.Min(1.72, (5.3 - gap * (rows - 1)) / rows);
        for (int i = 0; i < cards.Count; i++)
        {
            int row = i / cols;
            int col = i % cols;
            AddImageTile(
                shapes,
                800 + i * 10,
                cards[i],
                imageRelIds,
                0.9 + col * (cardW + gap),
                1.78 + row * (cardH + gap),
                cardW,
                cardH);
        }
    }

    private static void AddImageTile(
        List<XElement> shapes,
        int id,
        (string Id, string Uri) card,
        Dictionary<string, string> imageRelIds,
        double left,
        double top,
        double width,
        double height)
    {
        shapes.Add(Rect(id, Emu(left), Emu(top), Emu(width), Emu(height), C_PANEL));
        if (imageRelIds.TryGetValue(card.Uri, out var relId))
        {
            shapes.Add(Pic(id + 1, relId, Emu(left), Emu(top), Emu(width), Emu(height), card.Id));
        }
        else
        {
            shapes.Add(TextBox(id + 1, Emu(left + 0.12), Emu(top + 0.3), Emu(width - 0.24), Emu(0.4), "missing_asset: " + card.Uri, 11, C_MUTED, false, "ctr"));
        }
        shapes.Add(Rect(id + 2, Emu(left + 0.18), Emu(top + height - 0.48), Emu(Math.Min(2.75, width - 0.36)), Emu(0.3), C_BG_SOFT));
        shapes.Add(TextBox(id + 3, Emu(left + 0.3), Emu(top + height - 0.43), Emu(Math.Min(2.5, width - 0.55)), Emu(0.24), card.Id, 10.5, C_TEXT, true));
    }

    private static void Closing(List<XElement> shapes, string title, JsonElement blocks, string? logoRelId)
    {
        shapes.Add(Rect(3, 0, 0, Emu(13.333), Emu(7.5), C_BG));
        shapes.Add(GhostCircle(Emu(0.35), Emu(0.35), Emu(2.9), Emu(2.9)));
        if (logoRelId is not null)
        {
            shapes.Add(Pic(4, logoRelId, Emu(11.05), Emu(0.58), Emu(1.12), Emu(0.63), "DCC-MCP logo"));
        }
        shapes.Add(Rect(10, Emu(0.85), Emu(1.45), Emu(0.12), Emu(4.65), C_ACCENT));
        shapes.Add(TextBox(5, Emu(1.25), Emu(2.55), Emu(10.75), Emu(1.5), title.Length > 0 ? title : "Thanks", 52, C_TEXT, true, displayFont: true));
        if (blocks.ValueKind != JsonValueKind.Undefined)
        {
            foreach (var block in blocks.EnumerateArray())
            {
                if (block.TryGetProperty("type", out var type) && type.GetString() == "text")
                {
                    var paras = block.GetProperty("paragraphs").EnumerateArray().Select(p => p.GetString() ?? "").ToList();
                    shapes.Add(TextBox(6, Emu(1.28), Emu(4.38), Emu(8.8), Emu(0.85), string.Join("\n", paras), 19, C_MUTED, false));
                }
            }
        }
    }

    private static List<List<string>> BulletBlocks(JsonElement blocks)
    {
        var result = new List<List<string>>();
        if (blocks.ValueKind == JsonValueKind.Undefined)
        {
            return result;
        }
        foreach (var block in blocks.EnumerateArray())
        {
            if (block.TryGetProperty("type", out var type) && type.GetString() == "bullets" && block.TryGetProperty("items", out var items))
            {
                result.Add(items.EnumerateArray().Select(i => i.GetString() ?? "").ToList());
            }
        }
        return result;
    }

    private static List<string> FirstBulletItems(JsonElement blocks) =>
        BulletBlocks(blocks).FirstOrDefault() ?? new List<string>();

    private static string? FirstImageUri(JsonElement images)
    {
        if (images.ValueKind == JsonValueKind.Undefined)
        {
            return null;
        }
        foreach (JsonElement image in images.EnumerateArray())
        {
            if (image.TryGetProperty("uri", out JsonElement uri)
                && !string.IsNullOrWhiteSpace(uri.GetString()))
            {
                return uri.GetString();
            }
        }
        return null;
    }

    private static XElement RoundRect(int id, long x, long y, long cx, long cy, string fill, double radius)
    {
        var spPr = new XElement(P + "spPr",
            new XElement(A + "xfrm", new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)), new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy))),
            new XElement(A + "prstGeom", new XAttribute("prst", "roundRect"),
                new XElement(A + "avLst", new XElement(A + "gd", new XAttribute("name", "adj"), new XAttribute("fmla", "val " + (int)(radius * 100000))))),
            new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", fill))),
            new XElement(A + "ln", new XElement(A + "noFill")));
        return new XElement(P + "sp", NonVisualProps(id, null, "RoundRect", textBox: false), spPr, Style(), EmptyTxBody());
    }

    private static XElement GhostCircle(long x, long y, long cx, long cy)
    {
        var spPr = new XElement(P + "spPr",
            new XElement(A + "xfrm", new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)), new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy))),
            new XElement(A + "prstGeom", new XAttribute("prst", "ellipse"), new XElement(A + "avLst")),
            new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", C_GHOST))),
            new XElement(A + "ln", new XElement(A + "noFill")));
        return new XElement(P + "sp", NonVisualProps(999, null, "GhostCircle", textBox: false), spPr, Style(), EmptyTxBody());
    }

    private static XElement OvalOutlined(int id, long x, long y, long cx, long cy, string lineColor, string number)
    {
        var spPr = new XElement(P + "spPr",
            new XElement(A + "xfrm", new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)), new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy))),
            new XElement(A + "prstGeom", new XAttribute("prst", "ellipse"), new XElement(A + "avLst")),
            new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", C_BG))),
            new XElement(A + "ln", new XAttribute("w", "19050"), new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", lineColor)))));
        var txBody = new XElement(P + "txBody",
            new XElement(A + "bodyPr", new XAttribute("rtlCol", "0"), new XAttribute("anchor", "ctr")),
            new XElement(A + "lstStyle"),
            new XElement(A + "p", new XAttribute("algn", "ctr"),
                new XElement(A + "r",
                    new XElement(A + "rPr", new XAttribute("sz", "1200"), new XAttribute("b", "1"),
                        new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", lineColor))),
                        new XElement(A + "latin", new XAttribute("typeface", "Segoe UI")),
                        new XElement(A + "ea", new XAttribute("typeface", "Microsoft YaHei")),
                        new XElement(A + "cs", new XAttribute("typeface", "Segoe UI"))),
                    new XElement(A + "t", number))));
        return new XElement(P + "sp", NonVisualProps(id, null, "Oval", textBox: false), spPr, Style(), txBody);
    }

    private static XElement Connector(int id, long x1, long y1, long x2, long y2, string color)
    {
        var spPr = new XElement(P + "spPr",
            new XElement(A + "xfrm",
                new XElement(A + "off", new XAttribute("x", x1), new XAttribute("y", y1)),
                new XElement(A + "ext", new XAttribute("cx", Math.Max(0, x2 - x1)), new XAttribute("cy", Math.Max(0, y2 - y1)))),
            new XElement(A + "prstGeom", new XAttribute("prst", "line"), new XElement(A + "avLst")),
            new XElement(A + "ln", new XAttribute("w", "19050"), new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", color)))));
        var nv = new XElement(P + "nvCxnSpPr",
            new XElement(P + "cNvPr", new XAttribute("id", id), new XAttribute("name", "Connector " + id)),
            new XElement(P + "cNvCxnSpPr"),
            new XElement(P + "nvPr"));
        return new XElement(P + "cxnSp", nv, spPr, Style());
    }

    private static XElement Pic(int id, string relId, long x, long y, long cx, long cy, string alt)
    {
        var nvPicPr = new XElement(P + "nvPicPr",
            new XElement(P + "cNvPr", new XAttribute("id", id), new XAttribute("name", "Picture " + id), new XAttribute("descr", alt)),
            new XElement(P + "cNvPicPr"),
            new XElement(P + "nvPr"));
        var blipFill = new XElement(P + "blipFill",
            new XElement(A + "blip", new XAttribute(R + "embed", relId)),
            new XElement(A + "stretch", new XElement(A + "fillRect")));
        var spPr = new XElement(P + "spPr",
            new XElement(A + "xfrm", new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)), new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy))),
            new XElement(A + "prstGeom", new XAttribute("prst", "rect"), new XElement(A + "avLst")));
        return new XElement(P + "pic", nvPicPr, blipFill, spPr);
    }

    private static void FillShapeText(
        XElement shape,
        string text,
        double sizePt,
        string colorHex,
        bool bold,
        string align,
        bool displayFont = false)
    {
        var txBody = shape.Element(P + "txBody");
        if (txBody is null)
        {
            return;
        }
        txBody.RemoveNodes();
        var bodyPr = new XElement(A + "bodyPr", new XAttribute("rtlCol", "0"), new XAttribute("anchor", "t"));
        bodyPr.Add(new XElement(A + "normAutofit"));
        txBody.Add(bodyPr);
        txBody.Add(new XElement(A + "lstStyle"));
        string alignVal = align switch { "ctr" => "ctr", "r" => "r", _ => "l" };
        foreach (var line in text.Split('\n'))
        {
            var para = new XElement(A + "p", new XAttribute("algn", alignVal));
            var run = new XElement(A + "r",
                new XElement(A + "rPr",
                    new XAttribute("lang", "zh-CN"),
                    new XAttribute("sz", (int)(sizePt * 100)),
                    bold ? new XAttribute("b", "1") : null,
                    new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", colorHex))),
                    new XElement(A + "latin", new XAttribute("typeface", displayFont ? F_DISPLAY : F_BODY)),
                    new XElement(A + "ea", new XAttribute("typeface", "Microsoft YaHei")),
                    new XElement(A + "cs", new XAttribute("typeface", displayFont ? F_DISPLAY : F_BODY))),
                new XElement(A + "t", line));
            para.Add(run);
            txBody.Add(para);
        }
    }
    private const string C_BG = "0F141E";
    private const string C_BG_SOFT = "171F2E";
    private const string C_PANEL = "1E2A3D";
    private const string C_ACCENT = "4D9DE0";
    private const string C_ACCENT_2 = "7FC8A9";
    private const string C_TEXT = "E8ECF2";
    private const string C_MUTED = "9AA7BC";
    private const string C_GHOST = "223047";
    private const string F_DISPLAY = "DCC-MCP Display";
    private const string F_BODY = "DCC-MCP Body";

    private static XElement NotesSlideXml(
        string notes,
        string notesMasterRelId,
        string slideRelId,
        PresentationTemplatePackage template)
    {
        _ = notesMasterRelId;
        _ = slideRelId;

        var notesSlide = XDocument.Parse(template.Part("notes_slide")).Root!;
        var textElements = notesSlide.Descendants(A + "t").ToList();
        if (textElements.Count > 0)
        {
            textElements[0].Value = notes;
        }
        return notesSlide;
    }

    private static void ApplyTemplateStyle(
        XElement slide,
        PresentationTemplatePackage template)
    {
        PresentationTemplateStyle style = template.Style;
        var colors = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            [C_BG] = style.Background,
            [C_BG_SOFT] = style.BackgroundSoft,
            [C_PANEL] = style.Panel,
            [C_ACCENT] = style.Accent,
            [C_ACCENT_2] = style.AccentSecondary,
            [C_TEXT] = style.Text,
            [C_MUTED] = style.Muted,
            [C_GHOST] = style.Ghost,
        };
        foreach (XElement color in slide.Descendants(A + "srgbClr"))
        {
            XAttribute? value = color.Attribute("val");
            if (value is not null && colors.TryGetValue(value.Value, out string? replacement))
            {
                value.Value = replacement;
            }
        }
        foreach (XElement latin in slide.Descendants(A + "latin").Concat(slide.Descendants(A + "cs")))
        {
            string? role = latin.Attribute("typeface")?.Value;
            latin.SetAttributeValue(
                "typeface",
                string.Equals(role, F_DISPLAY, StringComparison.Ordinal)
                    ? style.LatinDisplayFont
                    : style.LatinFont);
        }
        foreach (XElement eastAsian in slide.Descendants(A + "ea"))
        {
            eastAsian.SetAttributeValue("typeface", style.EastAsianFont);
        }
        foreach (XElement text in slide.Descendants(A + "t"))
        {
            text.Value = text.Value.Replace(
                "dcc-mcp",
                template.BrandName,
                StringComparison.OrdinalIgnoreCase);
        }
    }

    // -- shape builders -----------------------------------------------------

    private static XElement ClrMap() =>
        new XElement(P + "clrMap",
            new XAttribute("bg1", "lt1"), new XAttribute("tx1", "dk1"), new XAttribute("bg2", "lt2"), new XAttribute("tx2", "dk2"),
            new XAttribute("accent1", "accent1"), new XAttribute("accent2", "accent2"), new XAttribute("accent3", "accent3"),
            new XAttribute("accent4", "accent4"), new XAttribute("accent5", "accent5"), new XAttribute("accent6", "accent6"),
            new XAttribute("hlink", "hlink"), new XAttribute("folHlink", "folHlink"));

    private static XElement Rect(int id, long x, long y, long cx, long cy, string fill)
    {
        var spPr = new XElement(P + "spPr",
            new XElement(A + "xfrm", new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)), new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy))),
            new XElement(A + "prstGeom", new XAttribute("prst", "rect"), new XElement(A + "avLst")),
            new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", fill))),
            new XElement(A + "ln", new XElement(A + "noFill")));
        return new XElement(P + "sp", NonVisualProps(id, null, "Background", textBox: false), spPr, Style(), EmptyTxBody());
    }

    private static XElement Oval(int id, long x, long y, long cx, long cy, string fill)
    {
        var spPr = new XElement(P + "spPr",
            new XElement(A + "xfrm", new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)), new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy))),
            new XElement(A + "prstGeom", new XAttribute("prst", "ellipse"), new XElement(A + "avLst")),
            new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", fill))),
            new XElement(A + "ln", new XElement(A + "noFill")));
        return new XElement(P + "sp", NonVisualProps(id, null, "Oval", textBox: false), spPr, Style(), EmptyTxBody());
    }

    private static XElement TextBox(
        int id,
        long x,
        long y,
        long cx,
        long cy,
        string text,
        double sizePt,
        string colorHex,
        bool bold,
        string align = "l",
        bool displayFont = false)
    {
        var spPr = new XElement(P + "spPr",
            new XElement(A + "xfrm", new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)), new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy))),
            new XElement(A + "prstGeom", new XAttribute("prst", "rect"), new XElement(A + "avLst")),
            new XElement(A + "noFill"),
            new XElement(A + "ln", new XElement(A + "noFill")));
        var txBody = new XElement(P + "txBody",
            new XElement(A + "bodyPr", new XAttribute("wrap", "square")),
            new XElement(A + "lstStyle"));
        string alignVal = align switch { "ctr" => "ctr", "r" => "r", _ => "l" };
        foreach (var line in text.Split('\n'))
        {
            var para = new XElement(A + "p", new XAttribute("algn", alignVal));
            var run = new XElement(A + "r",
                new XElement(A + "rPr",
                    new XAttribute("lang", "zh-CN"),
                    new XAttribute("sz", (int)(sizePt * 100)),
                    bold ? new XAttribute("b", "1") : null,
                    new XElement(A + "solidFill", new XElement(A + "srgbClr", new XAttribute("val", colorHex))),
                    new XElement(A + "latin", new XAttribute("typeface", displayFont ? F_DISPLAY : F_BODY)),
                    new XElement(A + "ea", new XAttribute("typeface", "Microsoft YaHei")),
                    new XElement(A + "cs", new XAttribute("typeface", displayFont ? F_DISPLAY : F_BODY))),
                new XElement(A + "t", line));
            para.Add(run);
            txBody.Add(para);
        }
        return new XElement(P + "sp", NonVisualProps(id, null, "TextBox", textBox: true), spPr, Style(), txBody);
    }

    private static XElement NonVisualProps(int id, string? placeholderType, string name, bool textBox = false)
    {
        var cNvSpPr = new XElement(P + "cNvSpPr");
        if (textBox)
        {
            cNvSpPr.Add(new XAttribute("txBox", "1"));
        }
        var nvSpPr = new XElement(P + "nvSpPr",
            new XElement(P + "cNvPr", new XAttribute("id", id), new XAttribute("name", name + " " + id)),
            cNvSpPr,
            new XElement(P + "nvPr"));
        if (placeholderType is not null)
        {
            var ph = new XElement(P + "ph", new XAttribute("type", placeholderType));
            if (placeholderType == "body")
            {
                ph.Add(new XAttribute("idx", "1"));
            }
            nvSpPr.Element(P + "nvPr")!.Add(ph);
        }
        return nvSpPr;
    }

    private static XElement BuildSpTree(params XElement[] children)
    {
        var spTree = new XElement(P + "spTree");
        spTree.Add(children);
        return spTree;
    }

    private static XElement[] GroupShapeProps(string id, long x, long y, long cx, long cy) =>
        new[]
        {
            new XElement(P + "nvGrpSpPr",
                new XElement(P + "cNvPr", new XAttribute("id", id), new XAttribute("name", "")),
                new XElement(P + "cNvGrpSpPr"),
                new XElement(P + "nvPr")),
            new XElement(P + "grpSpPr",
                new XElement(A + "xfrm",
                    new XElement(A + "off", new XAttribute("x", x), new XAttribute("y", y)),
                    new XElement(A + "ext", new XAttribute("cx", cx), new XAttribute("cy", cy)),
                    new XElement(A + "chOff", new XAttribute("x", 0), new XAttribute("y", 0)),
                    new XElement(A + "chExt", new XAttribute("cx", cx), new XAttribute("cy", cy)))),
        };

    private static XElement EmptyTxBody() => new XElement(P + "txBody",
        new XElement(A + "bodyPr", new XAttribute("rtlCol", "0"), new XAttribute("anchor", "ctr")),
        new XElement(A + "lstStyle"),
        new XElement(A + "p"));

    /// <summary>Neutral p:style block; geometry owns its fill/line/effect explicitly.</summary>
    private static XElement Style() =>
        new XElement(P + "style",
            new XElement(A + "lnRef", new XAttribute("idx", "0"), new XElement(A + "schemeClr", new XAttribute("val", "accent1"))),
            new XElement(A + "fillRef", new XAttribute("idx", "0"), new XElement(A + "schemeClr", new XAttribute("val", "accent1"))),
            new XElement(A + "effectRef", new XAttribute("idx", "0"), new XElement(A + "schemeClr", new XAttribute("val", "accent1"))),
            new XElement(A + "fontRef", new XAttribute("idx", "minor"), new XElement(A + "schemeClr", new XAttribute("val", "lt1"))));

    private static XElement[] StyleLevels(int sizeCentipoints) =>
        Enumerable.Range(1, 9)
            .Select(level => new XElement(A + $"lvl{level}pPr",
                new XElement(A + "defRPr", new XAttribute("sz", sizeCentipoints * 100))))
            .ToArray();

    private static XElement[] DefaultTextStyle() =>
        Enumerable.Range(1, 9)
            .Select(level => new XElement(A + $"lvl{level}pPr",
                new XElement(A + "defRPr", new XAttribute("sz", 1800))))
            .ToArray();

    private static XElement EffectStyle() =>
        new XElement(A + "effectStyle",
            new XElement(A + "effectLst",
                new XElement(A + "outerShdw",
                    new XAttribute("blurRad", "0"), new XAttribute("dist", "0"), new XAttribute("dir", "5400000"), new XAttribute("rotWithShape", "0"),
                    new XElement(A + "srgbClr", new XAttribute("val", "000000")),
                    new XElement(A + "alpha", new XAttribute("val", "0")))));

    private static XElement[] FillStyleList() =>
        new[]
        {
            new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr"))),
            new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr"))),
            new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr"))),
        };

    private static XElement[] LineStyleList() =>
        new[]
        {
            new XElement(A + "ln", new XAttribute("w", "9525"), new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr")))),
            new XElement(A + "ln", new XAttribute("w", "9525"), new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr")))),
            new XElement(A + "ln", new XAttribute("w", "9525"), new XElement(A + "solidFill", new XElement(A + "schemeClr", new XAttribute("val", "phClr")))),
        };

    private static long Emu(double inches) => (long)Math.Round(inches * EmuPerInch);

    private static PackagePart CreatePart(Package package, string uri, string contentType) =>
        package.CreatePart(new Uri(uri, UriKind.Relative), contentType, CompressionOption.Maximum);

    private static void WriteContent(PackagePart part, XElement content)
    {
        using var stream = part.GetStream();
        content.Save(stream);
    }
}
