<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>dcc-office-host</AssemblyName>
    <RootNamespace>Office.Automation.Host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Office.Automation.Runtime/Office.Automation.Runtime.csproj" />
    <ProjectReference Include="../Office.Automation.OpenXml/Office.Automation.OpenXml.csproj" />
  </ItemGroup>

</Project>
